### ISSUE TITLE
Erreur Connexion Client

### ISSUE THREAD

**Issue by dom-madrid** [ATM-Consulting/dolibarr_module_externalaccess#121]
Environement:
Ubuntu 18.04 Server
Apache 2.4.9
Mysql 5.7.36
PHP 7.2.24
Dolibarr 14.02

Version du module: 1.31.3 (source GIT)

Bug:
Apres installation et configuration sans problème, il n'est pas possible de se connecter comme client. 
L'accès à la page du portail fonctionne, mais il n'est pas possible de connecter (ni avec un utilisateur interne, ni avec un utilisateur externe). 
Message d'erreur : Failed to find user Array in Dolibarr database.

**Comment by atm-john** [comment]
Bonjour,

Merci de l’intérêt porté à notre module, cependant aucun dépannage ou assistance n'est donné sur git-hub, seul les clients projet et/ou Dolistore peuvent bénéficier d'une assistance en passant par notre service client.

Ceci étant dit, voici la première hypothèse  que je vérifierais : il est probable que vous utilisez un module perturbant le fonctionnement de la partie login du module car d’après le message d'erreur, vous envoyez un tableau et non une chaîne de caractère avec le formulaire de connexion.

Bonne journée et joyeuses fêtes.

**Comment by dom-madrid** [comment]
Bonsoir,

Merci de votre réponse et de votre hypothèse de recherche - je n'ai qu'un seul module qui affecte les utilisateurs, et un autre message d'erreur m'a confirmer la piste (la fonction de récupération de mot de passe est basé sur un Captcha qui m'avertit de la présence du module 2FA). J'ai donc trouvé le module qui posait problème et c'est bien dommage car il m'est indispensable pour le moment.  Il s'agit du module TWO-FACTOR AUTHENTICATION de InodBox. Voues devriez peut être regarder à rendre vos modules compatibles. Il faudra que je trouve une alternative pour mes accès clients.

Merci pour tout, Joyeuses Fêtes à toute l'équipe d'ATM.
