### ISSUE TITLE
Bug avec PHP8.0/8.1

### ISSUE THREAD

**Issue by E-Concept-Applications** [ATM-Consulting/dolibarr_module_externalaccess#169]
Bonjour,

J'ai installé le module sur un dolibarr v18.0.1, avec le module abricot 3.5.
Lorsque mon hébergement est en PHP 8.0 ou 8.1, j'obtiens une erreur 500 dans le navigateur quand je souhaites accéder au portail client. Pas de souci par contre en PHP 7.4 (mais comme il est obsolète, c'est moyen...)
J'ai également l'erreur suivante dans les logs du serveur :
`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Non-static method Context::getEntityMappingForCurrentDomain() cannot be called statically in /mypath/custom/externalaccess/www/master.inc.php:184\nStack trace:\n#0 /mypath/custom/externalaccess/www/main.inc.php(186): require_once()\n#1 /mypath/custom/externalaccess/www/config.php(24): include('...')\n#2 /mypath/custom/externalaccess/www/index.php(2): require('...')\n#3 {main}\n thrown in /mypath/custom/externalaccess/www/master.inc.php on line 184'`

Si ça peut aider à améliorer le module... :) 

Bonne soirée à tous ! :)

**Comment by kevimax** [comment]
Bonjour à tous :)

Même problème chez moi, même config.

Même erreur 500 avec le module bankimport. Peut être la même cause ?

Merci :D

**Comment by kevimax** [comment]
Re,
Fonctionne en supprimant :

$entitytotest = false;
if (!defined('NOREQUIREDB')) {
	require_once __DIR__.'/class/context.class.php';
	$entitytotest = Context::getEntityMappingForCurrentDomain();
	if($entitytotest){
		$conf->entity = $entitytotest;
	}
}

à la ligne 181 du fichier master.inc

Bonne soirée :)

**Comment by E-Concept-Applications** [comment]
Personnellement, je n'aime pas supprimer du code sans savoir pourquoi ça plante ^^' S'il était là, il y avait sûrement une raison.
Je regarderai si j'ai le temps si je trouve comment le débuguer. :) Sinon, en attendant, oui, ça peut être une solution provisoire.
