### ISSUE TITLE
Module Contrats

### ISSUE THREAD

**Issue by SBordier44** [ATM-Consulting/dolibarr_module_externalaccess#172]
Bonjour,

Avez-vous prévu prochainement de mettre en place l'accès aux contrats client (et documents liées) ?

Par avance, merci

**Comment by atm-john** [comment]
Bonjour,

le module évolue en fonction des demandes client et du financement par ces derniers et je n'ai pas connaissance de cette demande en R&D, je vous invite donc a contacter notre service commercial si cette fonctionnalité vous intéresse.

Bonne journée.
