### ISSUE TITLE
Blank page on config modules

### ISSUE THREAD

**Issue by webmasterproxy-media** [ATM-Consulting/dolibarr_module_externalaccess#23]
Hi ATM

I cant activate  the module on a fresh install v11.04 version on localhost on my mac

Abricot module activated

$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/Applications/MAMP/htdocs/mydolli/htdocs/custom';

**Comment by atm-john** [comment]
Hi, the answer (or a clue) is probably in your logs... without infos about error we can't answer.
