### ISSUE TITLE
Charte de nommage des releases

### ISSUE THREAD

**Issue by lmag** [ATM-Consulting/dolibarr_module_externalaccess#83]
Bonjour John,

La charte de nommage des releases ne permet pas une installation rapide par l'onglet déployer un module externe.
-Le zip n'est pas à la bonne charte de nommage devrait être : module_externalaccess-1.17.zip
-Le contenu : devrait être un dossier unique "externalaccess"

Laurent

**Comment by lmag** [comment]
[module_externalaccess-1.17.zip](https://github.com/ATM-Consulting/dolibarr_module_externalaccess/files/6829435/module_externalaccess-1.17.zip)

**Comment by lmag** [comment]
Si tu trouve une solution pour automatiser cela. Nous serions intéressé :)

**Comment by atm-john** [comment]
Bonjour,

Les fichiers au bon format sont sur le dolistore

les releases github servent juste de markeurs pour le readme... les vrais releases sont les branches et les fichiers zip du store (qui eux sont automatisés)
